version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:14
    container_name: cinemaabyss-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: cinemaabyss
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cinemaabyss-network

  # ZooKeeper for Kafka
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: cinemaabyss-zookeeper
    ports:
      - "2181:2181"
    networks:
      - cinemaabyss-network

  # Kafka
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    container_name: cinemaabyss-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "movie-events:1:1,user-events:1:1,payment-events:1:1"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - cinemaabyss-network

  # Monolith Service
  monolith:
    build:
      context: ./src/monolith
      dockerfile: Dockerfile
    container_name: cinemaabyss-monolith
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DB_CONNECTION_STRING: postgres://postgres:postgres_password@postgres:5432/cinemaabyss?sslmode=disable
    networks:
      - cinemaabyss-network

  # Movies Microservice
  movies-service:
    build:
      context: ./src/microservices/movies
      dockerfile: Dockerfile
    container_name: cinemaabyss-movies-service
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      PORT: 8081
      DB_CONNECTION_STRING: postgres://postgres:postgres_password@postgres:5432/cinemaabyss?sslmode=disable
    networks:
      - cinemaabyss-network

  # Events Microservice (PHP-FPM)
  events-php:
    build:
      context: ./src/microservices/events
      dockerfile: Dockerfile
    container_name: cinemaabyss-events-php
    healthcheck:
      test: ["CMD-SHELL", "cgi-fcgi -bind -connect 127.0.0.1:9000"]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - postgres
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092
    networks:
      - cinemaabyss-network

  # Events Microservice (Nginx)
  events-service:
    build:
      context: ./src/microservices/events
      dockerfile: Dockerfile.nginx
    container_name: cinemaabyss-events-service
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8002/api/events/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "8082:8082"
    volumes:
      - ./src/microservices/events:/var/www/html
      - ./src/microservices/events/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      events-php:
        condition: service_healthy
    networks:
      - cinemaabyss-network

  # Proxy Service (PHP-FPM)
  proxy-php:
    build:
      context: ./src/microservices/proxy
      dockerfile: Dockerfile
    container_name: cinemaabyss-proxy-php
    healthcheck:
      test: ["CMD-SHELL", "cgi-fcgi -bind -connect 127.0.0.1:9000"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MONOLITH_URL: http://monolith:8080
      MOVIES_SERVICE_URL: http://movies-service:8081
      EVENTS_SERVICE_URL: http://events-service:8082
      GRADUAL_MIGRATION: "true"
      MOVIES_MIGRATION_PERCENT: "50"
    networks:
      - cinemaabyss-network

  # Proxy Service (Nginx)
  proxy-service:
    build:
      context: ./src/microservices/proxy
      dockerfile: Dockerfile.nginx
    container_name: cinemaabyss-proxy-service
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8000/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "8000:8000"
    volumes:
      - ./src/microservices/proxy:/var/www/html
      - ./src/microservices/proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      proxy-php:
        condition: service_healthy
      monolith:
        condition: service_started
      movies-service:
        condition: service_started
      events-service:
        condition: service_healthy
    networks:
      - cinemaabyss-network

  # Kafka UI for monitoring Kafka
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: cinemaabyss-kafka-ui
    depends_on:
      - kafka
    ports:
      - "8090:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: cinemaabyss
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    networks:
      - cinemaabyss-network

volumes:
  postgres-data:

networks:
  cinemaabyss-network:
    name: cinemaabyss-network
    driver: bridge
