apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJnaGNyLmlvLyoiOiB7CgkJCSJhdXRoIjogImdocF9seXk4TzZwSjBNdHR3eER0c2FGVTFoMmNvaU41dFUxdmV4aDgiCgkJfQoJfQp9

type: kubernetes.io/dockerconfigjson
